4 rsvp confirmation
Shubham2301/phase2 pull request #10
Opened 2017-05-25 07:55 UTC by Shubham2301

2017-05-25 08:58 UTC, rathorevaibhav requested changes

2017-05-25 08:58 UTC, rathorevaibhav commented on public/wp-content/themes/ColoredCow/functions.php
> +function verify_field2()
please rename the function. The functionality is not clear from the name. It looks like it validates field2 but what exactly is field2?

2017-05-25 08:58 UTC, rathorevaibhav commented on public/wp-content/themes/ColoredCow/functions.php
> +    //echo $_POST['value'];
please remove comments

2017-05-25 08:58 UTC, rathorevaibhav commented on public/wp-content/themes/ColoredCow/functions.php
> +    //echo $post_verify_email;
remove comments.

2017-05-25 08:58 UTC, rathorevaibhav commented on public/wp-content/themes/ColoredCow/functions.php
> +    $datum = $wpdb->get_results("SELECT * FROM 23_sjpostmeta WHERE meta_value = '".$_POST['value']."'");
remove hardcoded table name. This query won't run on a system where wpdb prefix is different.

2017-05-25 08:58 UTC, rathorevaibhav commented on public/wp-content/themes/ColoredCow/functions.php
> +    $datum = $wpdb->get_results("SELECT * FROM 23_sjpostmeta WHERE meta_value = '".$_POST['value']."'");
use a better variable name?

2017-05-25 08:58 UTC, rathorevaibhav commented on public/wp-content/themes/ColoredCow/functions.php
> +        wp_die(json_encode("success"));
use wp_send_json_success(). It also has inbuilt wp_die. Please confirm.

2017-05-25 08:58 UTC, rathorevaibhav commented on public/wp-content/themes/ColoredCow/functions.php
> +        wp_die(json_encode("failed"));
use wp_send_json_error(). It also has inbuilt wp_die. Please confirm.

2017-05-25 08:58 UTC, rathorevaibhav commented on public/wp-content/themes/ColoredCow/functions.php
> +    wp_die();
Is this needed after if/else? since they already have wp_die.

2017-05-25 08:58 UTC, rathorevaibhav commented on public/wp-content/themes/ColoredCow/functions.php
> +add_action('wp_ajax_verify_field','verify_field2');
fix the name wp_ajax_verify_field and verify_field2.

2017-05-25 08:58 UTC, rathorevaibhav commented on public/wp-content/themes/ColoredCow/landing.php
> +	$args = array( 'post_type' => 'Soiree', 'posts_per_page' => 1 );
let's make all post_type names small cases.

2017-05-25 08:58 UTC, rathorevaibhav commented on public/wp-content/themes/ColoredCow/landing.php
> +		echo '<div class="soiree_name">';
ummm... remove HTML tags from echo statements?

2017-05-25 08:58 UTC, rathorevaibhav commented on public/wp-content/themes/ColoredCow/landing.php
> +				the_title();
use get_the_field() if you want to embed inside echo.

2017-05-25 08:58 UTC, rathorevaibhav commented on public/wp-content/themes/ColoredCow/rsvp.php
> +	echo '<div>';
remove HTML tags from PHP tags?

2017-05-25 08:58 UTC, rathorevaibhav commented on public/wp-content/themes/ColoredCow/src/js/main.js
> +    console.log("in main.js");
please remove debugging code.

2017-05-25 08:58 UTC, rathorevaibhav commented on public/wp-content/themes/ColoredCow/src/js/main.js
> +        console.log("submit field clicked");
remove. not needed.

2017-05-25 08:58 UTC, rathorevaibhav commented on public/wp-content/themes/ColoredCow/src/js/main.js
> +
spacing. formatting.

2017-05-25 08:58 UTC, rathorevaibhav commented on public/wp-content/themes/ColoredCow/src/js/main.js
> +    //var dataString = verification_form.serialize();
remove console statements and comments.

2017-05-25 08:58 UTC, rathorevaibhav commented on public/wp-content/themes/ColoredCow/src/js/main.js
> +    //console.log(dataString);
remove line 29 and 30.

2017-05-29 05:32 UTC, Shubham2301 commented
All changes made and reviewed. 
Closing this now.

2017-05-29 05:38 UTC, merged