#22 all events page
Shubham2301/phase2 pull request #29
Opened 2017-06-01 18:22 UTC by Shubham2301

PR for #22

2017-06-03 10:09 UTC, Shubham2301 commented
access test page from 
http://ec2-52-14-210-239.us-east-2.compute.amazonaws.com/all-soirees/

2017-06-03 10:54 UTC, rathorevaibhav commented
@Shubham2301 Please fix. Cannot open Soiree from "all soiree" page. The links don't take anywhere.

2017-06-03 12:51 UTC, rathorevaibhav commented
Something's not right on UI, I am able to scroll horizontally.
![image](https://cloud.githubusercontent.com/assets/12053186/26753683/6485e4a8-4889-11e7-809a-c10276bb4403.png)


See the whitespace right to the navbar.

Also, unable to open July Soiree. It should be a link. @Shubham2301 Please fix them before I further test.

2017-06-06 10:13 UTC, rathorevaibhav requested changes
just some basic changes. else everything is fine.

2017-06-06 10:13 UTC, rathorevaibhav commented on public/wp-content/themes/ColoredCow/all_soiree.php
> +						<?php echo ">"; endif;?><?php echo get_the_title();?></a></h1>
put echo ">" out of PHP tags?

2017-06-06 10:13 UTC, rathorevaibhav commented on public/wp-content/themes/ColoredCow/all_soiree.php
> +							<h1 class="page-title text-center"><?php if($current_date <= $last_date):?><a href="<?php echo get_home_url();?>"
breaking this line into multiple might help to make the code clean and non-confusing.

2017-06-06 10:13 UTC, rathorevaibhav commented on public/wp-content/themes/ColoredCow/header.php
> +                <li class = ""><a href = "<?php echo $link_all_soiree_page; ?>">All-Soirees</a></li>
class="" needed? please remove if not.

2017-06-06 10:14 UTC, rathorevaibhav commented
Looks good on testing. There's a bug that I've reference is issue #32. Let's track that later.

Please work on the review feedback and merge once done.

2017-06-06 10:55 UTC, merged